services:
  postgres:
    image: postgres
    ports:
      - 5000:5432
    hostname: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=learning_sql
    
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - postgres


volumes:
  postgres_data:
    driver: local